# Generated by Django 5.2.7 on 2025-12-06 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conducteur', '0001_initial'),
        ('passager', '0001_initial'),
        ('voiture', '0002_vehicule_nbrplaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('villeDep', models.CharField(max_length=50)),
                ('villeArr', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nbrPlaceDispo', models.IntegerField()),
                ('status', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En Cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('bagages', models.BooleanField(default=True)),
                ('animaux', models.BooleanField(default=False)),
                ('fumeur', models.BooleanField(default=False)),
                ('dateHeureDepart', models.DateTimeField()),
                ('dateHeureArrivee', models.DateTimeField()),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='conducteur.conducteur')),
                ('voiture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trajets', to='voiture.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idReservation', models.CharField(max_length=8, unique=True)),
                ('dateReservation', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('confirme', 'Confirmé'), ('en_attente', 'En Attente'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('nbrPlacesReservees', models.IntegerField(default=1)),
                ('passager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='passager.passager')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='trajet.trajet')),
            ],
        ),
    ]
