# Generated by Django 5.2.7 on 2025-10-18 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conducteur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(max_length=20)),
                ('modele', models.CharField(max_length=20)),
                ('couleur', models.CharField(max_length=20)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='conducteur.conducteur')),
            ],
        ),
    ]
