# Generated by Django 5.2.7 on 2025-11-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voiture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='nbrPlaces',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
