# Generated by Django 5.2.7 on 2025-10-18 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permisID', models.CharField(max_length=20)),
                ('nbrTrajet', models.IntegerField(default=0)),
                ('vehiculeMat', models.CharField(max_length=20)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conducteur_profile', to='utilisateur.utilisateur')),
            ],
        ),
    ]
