# Generated by Django 5.2.7 on 2025-10-19 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passager', '0001_initial'),
        ('trajet', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_place_reserve', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('passager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_passager', to='passager.passager')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_trajet', to='trajet.trajet')),
            ],
        ),
    ]
